//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ItemOrder = new HashSet<ItemOrder>();
        }
    
        public int id { get; set; }
        public int idClient { get; set; }
        public int idUser { get; set; }
        public decimal cost { get; set; }
        public System.DateTime dateOrder { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public int idStatus { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOrder> ItemOrder { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
